---

# Define package url (metric_beat_package_url) to perform specific version setup

- include: install/Debian.yml
  when: ansible_os_family == 'Debian' and metricbeat_package_url is not defined

- include: install/RedHat.yml
  when: ansible_os_family == 'RedHat' and metricbeat_package_url is not defined

- include: install/Archive.yml
  when: metricbeat_package_url is defined
# vi:ts=2:sw=2:et:ft=yaml
