---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  tags: metricbeat_install

- include: config.yml
  tags: metricbeat_config

- include: template.yml
  tags: metricbeat_template

- include: dashboards.yml
  tags: metricbeat_dashboards
  when: metricbeat_install_default_kibana_dashboards

- service:
    name: metricbeat
    enabled: yes
    state: started
  when: metricbeat_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
